# Generated by Django 4.2.19 on 2025-02-23 06:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('installation_date', models.DateField()),
                ('maintenance_interval_years', models.PositiveIntegerField(default=0)),
                ('maintenance_interval_months', models.PositiveIntegerField(default=0)),
                ('maintenance_interval_weeks', models.PositiveIntegerField(default=0)),
                ('maintenance_interval_days', models.PositiveIntegerField(default=0)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('non_operational', 'Non Operational'), ('under_maintenance', 'Under Maintenance')], default='operational', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.branch')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, help_text='Enter remarks for the maintenance performed.', null=True)),
                ('procedure', models.TextField(blank=True, help_text='Enter details of how the maintenance was performed.', null=True)),
                ('problems', models.TextField(blank=True, help_text='Describe problems that arose during maintenance.', null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Failed', 'Failed')], default='Not Started', help_text='What is the current status of the system maintenance?', max_length=15)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('assigned_technicians', models.ManyToManyField(help_text='The users who are assigned to perform the maintenace.', related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(help_text='Select the branch for this user.', on_delete=django.db.models.deletion.PROTECT, to='maintenance.branch')),
                ('equipment', models.ForeignKey(help_text='Select/Create an equipment.', on_delete=django.db.models.deletion.PROTECT, to='maintenance.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('part_number', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.branch')),
            ],
            options={
                'unique_together': {('part_number', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Describe the maintenance needed.')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the work order.', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the work order was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the work order was last updated.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.branch')),
                ('equipment', models.ForeignKey(help_text='Select the equipment that needs maintenance.', on_delete=django.db.models.deletion.PROTECT, to='maintenance.equipment')),
                ('requester', models.ForeignKey(help_text='The user requesting the maintenance.', on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MD manager', 'Maintenance Department Manager'), ('TEC', 'Technician'), ('MO', 'Maintenance Oversight'), ('CO', 'Chemical Oversight'), ('CL', 'Client'), ('AD', 'Admin')], max_length=50, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SparePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('WorkOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.workorder')),
                ('maintenance_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancerecord')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.sparepart')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.branch')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(help_text="Enter a type of maintenance (e.g., 'Software Installation').", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Enter a description of the maintenance type.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.branch')),
            ],
            options={
                'ordering': ['maintenance_type'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.ForeignKey(help_text='Select/Create a maintenance type.', on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenancetype'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='spare_parts',
            field=models.ManyToManyField(through='maintenance.SparePartUsage', to='maintenance.sparepart'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.manufacturer'),
        ),
        migrations.CreateModel(
            name='DecommissionedEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decommission_reason', models.TextField(blank=True, null=True)),
                ('decommission_date', models.DateField(default=django.utils.timezone.now)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(help_text='Enter the IUPAC or common name of the chemical.', max_length=255)),
                ('cas_number', models.CharField(help_text='Enter the Chemical Abstracts Service (CAS) registry number.', max_length=50, unique=True)),
                ('molecular_formula', models.CharField(blank=True, help_text='Enter the molecular formula of the chemical (if applicable).', max_length=100, null=True)),
                ('manufacturer_supplier', models.CharField(help_text='Enter the manufacturer or supplier name (brand/vendor).', max_length=255)),
                ('catalog_number', models.CharField(blank=True, help_text='Enter the catalog number (if sourced externally).', max_length=100, null=True)),
                ('batch_lot_number', models.CharField(blank=True, help_text='Enter the batch or lot number for tracking specific batches.', max_length=100, null=True)),
                ('quantity_available', models.FloatField(help_text='Enter the quantity available in stock (e.g., mL, L, g, kg).', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_of_measurement', models.CharField(choices=[('L', 'Liter (L)'), ('mL', 'Milliliter (mL)'), ('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('mg', 'Milligram (mg)'), ('mol', 'Mole (mol)'), ('mmol', 'Millimole (mmol)'), ('m³', 'Cubic Meter (m³)'), ('cm³', 'Cubic Centimeter (cm³)'), ('gal', 'Gallon (gal)'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('piece', 'Piece'), ('unit', 'Unit'), ('box', 'Box'), ('bottle', 'Bottle'), ('pack', 'Pack'), ('bag', 'Bag'), ('can', 'Can'), ('tube', 'Tube'), ('carton', 'Carton'), ('pallet', 'Pallet')], help_text='Select the unit of measurement', max_length=50)),
                ('location_storage_area', models.CharField(help_text='Enter the location or storage area (e.g., Shelf A, Lab 2, Flammable Cabinet).', max_length=255)),
                ('date_of_entry', models.DateField(default=django.utils.timezone.now, help_text='Enter the date when the chemical was added to inventory.')),
                ('expiration_date', models.DateField(blank=True, help_text='Enter the expiration date to track usability.', null=True)),
                ('reorder_level', models.FloatField(help_text='Enter the reorder level threshold to notify restocking needs.', validators=[django.core.validators.MinValueValidator(0)])),
                ('sds_link', models.URLField(blank=True, help_text='Enter the Safety Data Sheet (SDS) link for safety reference.', null=True)),
                ('hazard_classification', models.CharField(blank=True, help_text='Enter the hazard classification (e.g., GHS labeling, NFPA).', max_length=255, null=True)),
                ('usage_log', models.TextField(blank=True, help_text='Enter the history of usage and users handling the chemical.', null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.branch')),
            ],
            options={
                'verbose_name': 'Chemical',
                'verbose_name_plural': 'Chemicals',
                'ordering': ['chemical_name'],
            },
        ),
    ]
