# Generated by Django 5.1.6 on 2025-02-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='location',
        ),
    ]
