# Generated by Django 5.1.6 on 2025-04-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
