# Generated by Django 5.1.6 on 2025-04-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_taskcompletion_completed_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manufacturer',
            unique_together={('name', 'site')},
        ),
    ]
