# Generated by Django 5.1.6 on 2025-02-17 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_remove_branch_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('Location', models.CharField(max_length=50)),
                ('Installation_date', models.DateField()),
                ('maintenance_interval_years', models.PositiveIntegerField(default=0)),
                ('maintenance_interval_months', models.PositiveIntegerField(default=0)),
                ('maintenance_interval_weeks', models.PositiveIntegerField(default=0)),
                ('maintenance_interval_days', models.PositiveIntegerField(default=0)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('non_operational', 'Non Operational'), ('under_maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], default='operational', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.branch')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.manufacturer')),
            ],
        ),
    ]
