# Generated by Django 4.2.19 on 2025-02-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_equipment_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipment',
            name='unique_equipment_per_branch',
        ),
    ]
