# Generated by Django 4.2.19 on 2025-02-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_equipment_unique_equipment_per_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sparepart',
            unique_together=set(),
        ),
    ]
