# Generated by Django 5.1.6 on 2025-04-19 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_manufacturer_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='min_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('MD manager', 'Maintenance Department Manager'), ('TEC', 'Technician'), ('MO', 'Maintenance Oversight'), ('IM', 'Inventory Manager'), ('CL', 'Client'), ('AD', 'Admin')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SparePartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField()),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Issued', 'Issued'), ('Used', 'Used'), ('Returned', 'Returned'), ('canceled', 'canceled')], default='Requested', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('use_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('return_condition', models.TextField(blank=True)),
                ('return_accepted', models.BooleanField(default=False)),
                ('inventory_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_spare_part_requests', to=settings.AUTH_USER_MODEL)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.sparepart')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddField(
            model_name='sparepartusage',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.sparepartrequest'),
        ),
        migrations.CreateModel(
            name='SparePartTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Request', 'Request'), ('Approval', 'Approval'), ('Issuance', 'Issuance'), ('Usage', 'Usage'), ('Return', 'Return'), ('cancel', 'cancel')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='maintenance.sparepartrequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
