# Generated by Django 5.1.6 on 2025-02-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_manufacturer_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='Installation_date',
            new_name='installation_date',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Location',
            new_name='location',
        ),
    ]
