# Generated by Django 5.1.6 on 2025-02-18 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_rename_installation_date_equipment_installation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('part_number', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.branch')),
            ],
            options={
                'unique_together': {('part_number', 'branch')},
            },
        ),
    ]
