# Generated by Django 4.2.19 on 2025-02-23 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0004_alter_sparepart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='assigned_technicians',
            field=models.ManyToManyField(related_name='maintenance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.branch'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.equipment'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenancetype'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='problems',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='procedure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Approved', 'Approved'), ('Failed', 'Failed')], default='Not Started', max_length=15),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
