# Generated by Django 5.1.6 on 2025-04-19 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_sparepart_is_active_sparepart_min_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartrequest',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spareparttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Request', 'Request'), ('Approval', 'Approval'), ('Issuance', 'Issuance'), ('Usage', 'Usage'), ('Return', 'Return'), ('cancellation', 'cancellation')], max_length=20),
        ),
    ]
