# Generated by Django 4.2.19 on 2025-02-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenancerecord_accepted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='accepted_by',
        ),
    ]
