# Generated by Django 5.1.6 on 2025-04-21 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_sparepartrequest_cancel_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Issued', 'Issued'), ('Received', 'Received'), ('Used', 'Used'), ('Returned', 'Returned'), ('canceled', 'canceled')], default='Requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='spareparttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Request', 'Request'), ('Approval', 'Approval'), ('Issuance', 'Issuance'), ('Usage', 'Usage'), ('Return', 'Return'), ('cancellation', 'cancellation'), ('Receipt', 'Receipt')], max_length=20),
        ),
        migrations.CreateModel(
            name='TechnicianSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.IntegerField(default=0)),
                ('used_quantity', models.IntegerField(default=0)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.sparepart')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('technician', 'spare_part')},
            },
        ),
    ]
