# Generated by Django 5.1.6 on 2025-04-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_sparepartrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciansparepart',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
