# Generated by Django 4.2.19 on 2025-02-24 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0006_remove_maintenancerecord_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='requester',
            field=models.ForeignKey(help_text='The user requesting the maintenance.', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
