# Generated by Django 4.2.19 on 2025-02-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_chemicals_maintenancerecord_maintenancetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicals',
            name='unit_of_measurement',
            field=models.CharField(choices=[('L', 'Liter (L)'), ('mL', 'Milliliter (mL)'), ('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('mg', 'Milligram (mg)'), ('mol', 'Mole (mol)'), ('mmol', 'Millimole (mmol)'), ('m³', 'Cubic Meter (m³)'), ('cm³', 'Cubic Centimeter (cm³)'), ('gal', 'Gallon (gal)'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('piece', 'Piece'), ('unit', 'Unit'), ('box', 'Box'), ('bottle', 'Bottle'), ('pack', 'Pack'), ('bag', 'Bag'), ('can', 'Can'), ('tube', 'Tube'), ('carton', 'Carton'), ('pallet', 'Pallet')], help_text='Select the unit of measurement', max_length=50),
        ),
    ]
