# Generated by Django 4.2.19 on 2025-02-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_workorder_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='location',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('accepted', 'accepted'), ('Completed', 'Completed'), ('approved', 'approved')], default='Pending', help_text='Current status of the work order.', max_length=15),
        ),
    ]
