# Generated by Django 4.2.19 on 2025-02-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_chemicals_unit_of_measurement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chemicals',
            new_name='Chemical',
        ),
    ]
