# Generated by Django 5.1.6 on 2025-04-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_techniciansparepart_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniciansparepart',
            name='available_quantity',
        ),
    ]
