# Generated by Django 5.1.6 on 2025-04-21 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_remove_techniciansparepart_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciansparepart',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_inventory_records', to='maintenance.sparepartrequest'),
        ),
    ]
