# Generated by Django 5.1.6 on 2025-02-19 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_rename_chemicals_chemical'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maintenance.branch'),
            preserve_default=False,
        ),
    ]
