# Generated by Django 4.2.19 on 2025-02-24 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0008_workorder_location_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assigned_technicians',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
