# Generated by Django 4.2.19 on 2025-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_workorder_assigned_technicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Complete', 'Complete'), ('Approved', 'Approved')], default='Pending', help_text='Current status of the work order.', max_length=15),
        ),
    ]
