# Generated by Django 5.1.6 on 2025-02-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_chemical_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='maintenance_for',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='work_order',
        ),
    ]
