# Generated by Django 5.1.6 on 2025-04-22 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_techniciansparepart_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartrequest',
            name='is_return_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='original_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.sparepartrequest'),
        ),
        migrations.AlterField(
            model_name='sparepartrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Issued', 'Issued'), ('Received', 'Received'), ('Used', 'Used'), ('Return_Requested', 'Return Requested'), ('Return_Accepted', 'Return Accepted'), ('Returned', 'Returned'), ('canceled', 'canceled')], default='Requested', max_length=20),
        ),
    ]
