# Generated by Django 4.2.19 on 2025-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='spare_parts',
            field=models.ManyToManyField(through='maintenance.SparePartUsage', to='maintenance.sparepart'),
        ),
    ]
