# Generated by Django 5.1.6 on 2025-02-20 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_remove_maintenancerecord_maintenance_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartusage',
            name='WorkOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.workorder'),
        ),
        migrations.AlterField(
            model_name='sparepartusage',
            name='maintenance_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancerecord'),
        ),
    ]
