# Generated by Django 5.1.6 on 2025-04-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_sparepartrequest_is_return_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartrequest',
            name='original_request',
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='return_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='return_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='return_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sparepartrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Issued', 'Issued'), ('Received', 'Received'), ('canceled', 'canceled'), ('Return_Request', 'Return Request'), ('Return_Accepted', 'Accepted Returns'), ('Returned', 'Returned')], default='Requested', max_length=20),
        ),
    ]
