# Generated by Django 4.2.19 on 2025-02-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_sparepartusage_workorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='department',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('MD', 'Maintenance Department'), ('CD', 'Chemicals Department')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('MD manager', 'Maintenance Department Manager'), ('TEC', 'Technician'), ('MO', 'Maintenance Oversight'), ('CO', 'Chemical Oversight'), ('CL', 'Client'), ('AD', 'Admin')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
