# Generated by Django 5.1.6 on 2025-04-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_remove_sparepartrequest_original_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparttransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
