# Generated by Django 4.2.19 on 2025-02-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_workorder_spare_parts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparepartusage',
            old_name='WorkOrder',
            new_name='work_order',
        ),
    ]
