# Generated by Django 4.2.19 on 2025-02-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_remove_role_department_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
    ]
