# Generated by Django 4.2.19 on 2025-02-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_rename_workorder_sparepartusage_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
