# Generated by Django 5.1.6 on 2025-04-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_alter_spareparttransaction_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sparepartrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Issued', 'Issued'), ('Received', 'Received'), ('Canceled', 'Canceled'), ('Return_Request', 'Return Request'), ('Return_Accepted', 'Accepted Returns'), ('Returned', 'Returned')], default='Requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='spareparttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Request', 'Request'), ('Approval', 'Approval'), ('Issuance', 'Issuance'), ('Usage', 'Usage'), ('Return', 'Return'), ('Cancellation', 'Cancellation'), ('Receipt', 'Receipt')], max_length=20),
        ),
    ]
