# Generated by Django 5.1.6 on 2025-02-24 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='last_restock_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='RestockSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('restock_date', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='restock_attachments/')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.sparepart')),
            ],
        ),
    ]
