# Generated by Django 5.1.6 on 2025-02-26 13:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_sparepart_last_restock_date_restocksparepart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('purpose', models.TextField()),
                ('date_used', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_usage', to='maintenance.branch')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='maintenance.chemical')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
