# Generated by Django 5.1.6 on 2025-08-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_alter_equipment_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_quarterly_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='next_quarterly_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual')], max_length=20),
        ),
    ]
