# Generated by Django 5.1.6 on 2025-08-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_equipment_last_quarterly_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_quarterly_notification_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
