# Generated by Django 5.1.6 on 2025-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_equipment_last_quarterly_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='spare_part_request_attachments/'),
        ),
    ]
