# Generated by Django 5.1.6 on 2025-03-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_restockchemical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalusage',
            name='chemical',
        ),
        migrations.RemoveField(
            model_name='restockchemical',
            name='chemical',
        ),
        migrations.RemoveField(
            model_name='chemicalusage',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='chemicalusage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chemical',
        ),
        migrations.DeleteModel(
            name='RestockChemical',
        ),
        migrations.DeleteModel(
            name='ChemicalUsage',
        ),
    ]
