# Generated by Django 5.1.6 on 2025-03-03 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_remove_chemicalusage_chemical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(help_text="Enter a type of maintenance (e.g., 'Software Installation').", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Enter a description of the maintenance type.')),
            ],
            options={
                'ordering': ['equipment_type'],
            },
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='maintenance_type',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='maintenance_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenancetask'),
        ),
        migrations.DeleteModel(
            name='MaintenanceType',
        ),
    ]
