# Generated by Django 5.1.6 on 2025-08-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_sparepartrequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='work_order_receipts/', verbose_name='Payment Receipt'),
        ),
    ]
