# Generated by Django 5.1.6 on 2025-03-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_maintenancetask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('biannually', 'Biannually'), ('annually', 'Annually')], max_length=20)),
                ('maintenance_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_groups', to='maintenance.maintenancetask')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Enter a description of the task.')),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='maintenance.taskgroup')),
            ],
        ),
    ]
