# Generated by Django 5.1.6 on 2025-08-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_workorder_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='restocksparepart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
