# Generated by Django 5.1.6 on 2025-03-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_taskgroup_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='List of subtasks or checklist items.'),
        ),
    ]
