# Generated by Django 5.1.6 on 2025-03-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_subtask_remove_task_checklist_task_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='task',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='List of subtasks or checklist items.'),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
