# Generated by Django 5.1.6 on 2025-03-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_remove_task_subtasks_task_checklist_delete_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='checklist',
        ),
    ]
