# Generated by Django 5.1.6 on 2025-03-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='maintenance_interval_days',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='maintenance_interval_months',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='maintenance_interval_weeks',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='maintenance_interval_years',
        ),
    ]
