# Generated by Django 5.1.6 on 2025-03-04 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_remove_equipment_maintenance_interval_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='accepted_by',
            field=models.ManyToManyField(blank=True, related_name='accepted_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancerecord')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.task')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='completed_tasks',
            field=models.ManyToManyField(through='maintenance.TaskCompletion', to='maintenance.task'),
        ),
    ]
