# Generated by Django 5.1.6 on 2025-03-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0026_maintenancerecord_accepted_by_taskcompletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('biannual', 'Biannual'), ('annual', 'Annual')], max_length=20, null=True),
        ),
    ]
