# Generated by Django 5.1.6 on 2025-03-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0028_equipment_last_annual_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='equipment',
            field=models.ForeignKey(help_text='Select the equipment that needs maintenance.', null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.equipment'),
        ),
    ]
