# Generated by Django 4.2.19 on 2025-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0029_alter_workorder_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_notification_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
