# Generated by Django 5.1.6 on 2025-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0030_equipment_last_notification_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
    ]
