# Generated by Django 5.1.6 on 2025-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0033_maintenancerecord_rejected_by_workorder_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
