# Generated by Django 5.1.6 on 2025-03-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0034_workorder_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='last_notification_sent',
            new_name='last_annual_notification_sent',
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_biannual_notification_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_monthly_notification_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
