# Generated by Django 5.1.6 on 2025-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0035_rename_last_notification_sent_equipment_last_annual_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='decommissioned',
            field=models.BooleanField(default=False),
        ),
    ]
