# Generated by Django 5.1.6 on 2025-03-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0036_equipment_decommissioned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(default='Not Started', max_length=15),
        ),
    ]
