# Generated by Django 5.1.6 on 2025-03-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0037_alter_maintenancerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Approved', 'Approved'), ('Failed', 'Failed')], default='Not Started', max_length=15),
        ),
    ]
