# Generated by Django 5.1.6 on 2025-03-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0038_alter_maintenancerecord_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('equipment_type', 'serial_number')},
        ),
    ]
