# Generated by Django 5.1.6 on 2025-04-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0039_alter_equipment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
