# Generated by Django 5.1.6 on 2025-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0040_workorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
