# Generated by Django 5.1.6 on 2025-03-03 06:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0017_remove_chemicalusage_chemical_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(help_text='Enter the IUPAC or common name of the chemical.', max_length=255)),
                ('cas_number', models.CharField(help_text='Enter the Chemical Abstracts Service (CAS) registry number.', max_length=50, unique=True)),
                ('molecular_formula', models.CharField(blank=True, help_text='Enter the molecular formula of the chemical (if applicable).', max_length=100, null=True)),
                ('manufacturer_supplier', models.CharField(help_text='Enter the manufacturer or supplier name (brand/vendor).', max_length=255)),
                ('catalog_number', models.CharField(blank=True, help_text='Enter the catalog number (if sourced externally).', max_length=100, null=True)),
                ('batch_lot_number', models.CharField(blank=True, help_text='Enter the batch or lot number for tracking specific batches.', max_length=100, null=True)),
                ('quantity_available', models.FloatField(help_text='Enter the quantity available in stock (e.g., mL, L, g, kg).', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_of_measurement', models.CharField(choices=[('L', 'Liter (L)'), ('mL', 'Milliliter (mL)'), ('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('mg', 'Milligram (mg)'), ('mol', 'Mole (mol)'), ('mmol', 'Millimole (mmol)'), ('m³', 'Cubic Meter (m³)'), ('cm³', 'Cubic Centimeter (cm³)'), ('gal', 'Gallon (gal)'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('piece', 'Piece'), ('unit', 'Unit'), ('box', 'Box'), ('bottle', 'Bottle'), ('pack', 'Pack'), ('bag', 'Bag'), ('can', 'Can'), ('tube', 'Tube'), ('carton', 'Carton'), ('pallet', 'Pallet')], help_text='Select the unit of measurement', max_length=50)),
                ('location_storage_area', models.CharField(help_text='Enter the location or storage area (e.g., Shelf A, Lab 2, Flammable Cabinet).', max_length=255)),
                ('date_of_entry', models.DateField(default=django.utils.timezone.now, help_text='Enter the date when the chemical was added to inventory.')),
                ('expiration_date', models.DateField(blank=True, help_text='Enter the expiration date to track usability.', null=True)),
                ('reorder_level', models.FloatField(help_text='Enter the reorder level threshold to notify restocking needs.', validators=[django.core.validators.MinValueValidator(0)])),
                ('sds_link', models.URLField(blank=True, help_text='Enter the Safety Data Sheet (SDS) link for safety reference.', null=True)),
                ('hazard_classification', models.CharField(blank=True, help_text='Enter the hazard classification (e.g., GHS labeling, NFPA).', max_length=255, null=True)),
                ('usage_log', models.TextField(blank=True, help_text='Enter the history of usage and users handling the chemical.', null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.branch')),
            ],
            options={
                'verbose_name': 'Chemical',
                'verbose_name_plural': 'Chemicals',
                'ordering': ['chemical_name'],
            },
        ),
        migrations.CreateModel(
            name='ChemicalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('purpose', models.TextField()),
                ('date_used', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_usage', to='maintenance.branch')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='chemical.chemical')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestockChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('restock_date', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='restock_attachments/')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chemical.chemical')),
            ],
        ),
    ]
